<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $module_1 = [
//            now dashboards' permission list******************************************************************
            [
                'module_id' => 1,
                'name' => 'Index Dashboard',
                'route' => 'backend.dashboard.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            now dashboards' permission list******************************************************************
        ];
        $module_2 = [
//            now roles' permission list*************************************************************************
            [
                'module_id' => 2,
                'name' => 'Index Role',
                'route' => 'backend.role.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Create Role',
                'route' => 'backend.role.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Store Role',
                'route' => 'backend.role.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Show Role',
                'route' => 'backend.role.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Edit Role',
                'route' => 'backend.role.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Update Role',
                'route' => 'backend.role.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Delete Role',
                'route' => 'backend.role.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Trash Role',
                'route' => 'backend.role.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Restore Role',
                'route' => 'backend.role.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Force Delete Role',
                'route' => 'backend.role.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Assign Permission Role',
                'route' => 'backend.role.assignPermission',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'Post Permission Role',
                'route' => 'backend.role.postPermission',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end roles' permission list*************************************************************************
        ];
        $module_3 = [
//            now modules' permission list*************************************************************************
            [
                'module_id' => 3,
                'name' => 'Index Module',
                'route' => 'backend.module.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Create Module',
                'route' => 'backend.module.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Store Module',
                'route' => 'backend.module.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Show Module',
                'route' => 'backend.module.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Edit Module',
                'route' => 'backend.module.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Update Module',
                'route' => 'backend.module.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Delete Module',
                'route' => 'backend.module.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Trash Module',
                'route' => 'backend.module.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Restore Module',
                'route' => 'backend.module.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'Force Delete Module',
                'route' => 'backend.module.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end modules' permission list*************************************************************************
        ];
        $module_4 = [
//            now permissions' permission list*************************************************************************

            [
                'module_id' => 4,
                'name' => 'Index Permission',
                'route' => 'backend.permission.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Create Permission',
                'route' => 'backend.permission.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Store Permission',
                'route' => 'backend.permission.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Show Permission',
                'route' => 'backend.permission.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Edit Permission',
                'route' => 'backend.permission.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Update Permission',
                'route' => 'backend.permission.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Delete Permission',
                'route' => 'backend.permission.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Trash Permission',
                'route' => 'backend.permission.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Restore Permission',
                'route' => 'backend.permission.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'Force Delete Permission',
                'route' => 'backend.permission.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end permissions' permission list*************************************************************************
        ];
        $module_5 = [
//            now genders' permission list*************************************************************************
            [
                'module_id' => 5,
                'name' => 'Index Gender',
                'route' => 'backend.gender.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Create Gender',
                'route' => 'backend.gender.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Store Gender',
                'route' => 'backend.gender.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Show Gender',
                'route' => 'backend.gender.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Edit Gender',
                'route' => 'backend.gender.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Update Gender',
                'route' => 'backend.gender.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Delete Gender',
                'route' => 'backend.gender.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Trash Gender',
                'route' => 'backend.gender.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Restore Gender',
                'route' => 'backend.gender.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'Force Delete Gender',
                'route' => 'backend.gender.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end genders' permission list*************************************************************************
        ];
        $module_6 = [
//            now profiles' permission list*************************************************************************
            [
                'module_id' => 6,
                'name' => 'Index Profile',
                'route' => 'backend.profile.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Create Profile',
                'route' => 'backend.profile.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Store Profile',
                'route' => 'backend.profile.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Show Profile',
                'route' => 'backend.profile.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Edit Profile',
                'route' => 'backend.profile.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Update Profile',
                'route' => 'backend.profile.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'Delete Profile',
                'route' => 'backend.profile.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end profiles' permission list*************************************************************************
        ];
        $module_7 = [
//            now settings' permission list*************************************************************************
            [
                'module_id' => 7,
                'name' => 'Index Setting',
                'route' => 'backend.setting.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Create Setting',
                'route' => 'backend.ward.create',
                'status' => 1,
                'created_by'  => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Store Setting',
                'route' => 'backend.ward.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Show Setting',
                'route' => 'backend.ward.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Edit Setting',
                'route' => 'backend.ward.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Update Setting',
                'route' => 'backend.ward.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'Delete Setting',
                'route' => 'backend.ward.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end settings' permission list*************************************************************************
        ];
        $module_8 = [
//            now Categories' permission list*************************************************************************
            [
                'module_id' => 8,
                'name' => 'Index Category',
                'route' => 'backend.category.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Create Category',
                'route' => 'backend.category.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Store Category',
                'route' => 'backend.category.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Show Category',
                'route' => 'backend.category.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Edit Category',
                'route' => 'backend.category.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Update Category',
                'route' => 'backend.category.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Delete Category',
                'route' => 'backend.category.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'module_id' => 8,
                'name' => 'Trash Category',
                'route' => 'backend.category.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Restore Category',
                'route' => 'backend.category.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'Force Delete Category',
                'route' => 'backend.category.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end Categories' permission list*************************************************************************
        ];
        $module_9 = [
//            now Categories' permission list*************************************************************************
            [
                'module_id' => 9,
                'name' => 'Index Subcategory',
                'route' => 'backend.subcategory.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Create Subcategory',
                'route' => 'backend.subcategory.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Store Subcategory',
                'route' => 'backend.subcategory.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Show Subcategory',
                'route' => 'backend.subcategory.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Edit Subcategory',
                'route' => 'backend.subcategory.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Update Subcategory',
                'route' => 'backend.subcategory.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Delete Subcategory',
                'route' => 'backend.subcategory.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'module_id' => 9,
                'name' => 'Trash Subcategory',
                'route' => 'backend.subcategory.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Restore Subcategory',
                'route' => 'backend.subcategory.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'Force Delete Subcategory',
                'route' => 'backend.subcategory.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end Categories' permission list*************************************************************************
        ];
        $module_10 = [
//            now Categories' permission list*************************************************************************
            [
                'module_id' => 10,
                'name' => 'Index Author',
                'route' => 'backend.author.index',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Create Author',
                'route' => 'backend.author.create',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Store Author',
                'route' => 'backend.author.store',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Show Author',
                'route' => 'backend.author.show',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Edit Author',
                'route' => 'backend.author.edit',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Update Author',
                'route' => 'backend.author.update',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Delete Author',
                'route' => 'backend.author.destroy',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'module_id' => 10,
                'name' => 'Trash Author',
                'route' => 'backend.author.trash',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Restore Author',
                'route' => 'backend.author.restore',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'Force Delete Author',
                'route' => 'backend.author.forceDelete',
                'status' => 1,
                'created_by'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
//            end Categories' permission list*************************************************************************
        ];
        $permissions = array_merge(
            $module_1,
            $module_2,
            $module_3,
            $module_4,
            $module_5,
            $module_6,
            $module_7,
            $module_8,
            $module_9,
            $module_10,
        );

        DB::table('permissions')->insert($permissions);
    }
}
